Repository the-collab-lab/tcl-34-smart-shopping-list, pull requests merged in 2021-11, with the labels that each got.

#24 List filter
  src/components/add-form/index.js
  src/components/add-form/styles.css
  src/components/show-products/index.js
  src/components/show-products/styles.css
  src/pages/List/styles.css
  src/utils/getFilteredResults.js
  src/utils/normalizeFilter.js
Labels: enhancement

#25 Save estimated next purchase in Firestore
  src/components/show-products/index.js
  src/helpers/firebaseHelpers.js
  src/pages/AddItem/index.js
  src/utils/compareDates.js
  src/utils/daysSinceLastTransaction.js
  src/utils/diffBetweenTodayAndDate.js
  src/utils/findProductById.js
  src/utils/firebaseUtils.js
Labels: enhancement

#29 Hotfix: solve add new product
  src/pages/AddItem/index.js
Labels: bug

#30 Delete products
  package-lock.json
  src/components/show-products/index.js
  src/components/show-products/styles.css
  src/utils/firebaseUtils.js
Labels: enhancement

#31 Ordering products by time and name
  src/components/show-products/index.js
  src/components/show-products/styles.css
  src/helpers/firebaseHelpers.js
  src/hooks/useProducts.js
  src/utils/nextPurchaseDay.js
  src/utils/sortProductsByTime.js
  src/utils/timeFrames.js
Labels: documentation, enhancement

#37 List Page
  package-lock.json
  package.json
  public/index.html
  src/App.css
  src/components/content-container/index.js
  src/components/content-container/styles.css
  src/components/join-list/index.js
  src/components/join-list/styles.css
  src/components/routing/Navigation/index.js
  src/components/routing/Navigation/styles.css
  src/components/show-products/checkbox-styles.css
  src/components/show-products/index.js
  src/components/show-products/styles.css
  src/pages/AddItem/index.js
  src/pages/AddItem/styles.css
  src/pages/List/index.js
  src/pages/pages-styles.css
  src/pages/shopping-add-image.svg
Labels: enhancement

#33 Welcome view
  public/index.html
  src/App.css
  src/components/add-form/styles.css
  src/components/join-list/index.js
  src/pages/AddItem/styles.css
  src/pages/Welcome/index.js
  src/pages/Welcome/shopping-welcome-image.svg
  src/pages/Welcome/style.css
Labels: enhancement

#41 [Bug] Time frames radio group
  src/components/add-form/index.js
  src/components/add-form/styles.css
  src/components/radio-input/index.js
  src/components/routing/Navigation/index.js
  src/components/routing/Navigation/styles.css
Labels: bug

#46 [BUG] Disable Checkbox
  src/components/show-products/index.js
Labels: bug

#50 Fix inactive criteria
  src/components/add-form/index.js
  src/helpers/firebaseHelpers.js
  src/utils/getKeyByValue.js
  src/utils/nextPurchaseDay.js
  src/utils/timeFrames.js
Labels: bug, enhancement
